In [7]:
import numpy as np
a=np.array([1,2,3],dtype=str)
print(a)

['1' '2' '3']


In [3]:
#more than one dimensiom
import numpy as np
a= np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [1]:
#minium dimension
import numpy as np
a=np.array([1,2,3,4,5],ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [4]:
#dtype parameter
import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [5]:
# using array -scalar type
import numpy as np
dt=np.dtype(np.int32)
print(dt)


int32


In [10]:
x=np.array([12.20])
print(x.dtype)

float64


In [13]:
dt=np.dtype('i8')
print(dt)

int64


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [15]:
# this resize the ndarray
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
b=a.reshape(6,1)
print(b)

[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [24]:
z=np.zeros((6))
print(z)

[0. 0. 0. 0. 0. 0.]


In [25]:
z=np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
z=np.ones(5)
print(z)

[1. 1. 1. 1. 1.]


In [27]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [30]:
# now reshape it
b=np.ones([4,6],dtype=int)
b=b.reshape(2,4,3)
print(b)


[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [35]:
x=np.empty([3,2],dtype=int)
print(x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [38]:
x=np.eye((3),dtype=int)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
x=np.arange(36).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
#find diagonal
a=np.diag(x)
a

array([ 0,  7, 14, 21, 28, 35])

In [41]:
x=np.array([12,2,33,44,55,6])
np.diag(x)

array([[12,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0],
       [ 0,  0,  0,  0, 55,  0],
       [ 0,  0,  0,  0,  0,  6]])

In [1]:
#arange method
import numpy as np
a=np.arange(24)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [3]:
# this is one dimensional array
import numpy as np
a=np.arange(24)
a.ndim

1

In [4]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [6]:
#start and stop parameters set 
import numpy as np
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [7]:
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [13]:
x=np.linspace(10,20,7,retstep=True)
print(x)

(array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ]), 1.6666666666666667)


In [12]:
# endpoint set to false
import numpy as np
x=np.linspace(10,20,5, endpoint=False,retstep=True)
print(x)

(array([10., 12., 14., 16., 18.]), 2.0)


In [14]:
x=np.linspace(1,2,5,retstep=True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [15]:
#convert list to ndarray
import numpy as np
x=[1,2,3]
print(type(x))
a=np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [16]:
#ndaray from tuple
import numpy as np
x=(1,3,4,)
a=np.asarray(x)
print(a)

[1 3 4]


In [20]:
x=[(1,2,43),(3,4,4)]
a=np.asarray(x)
print(a)

[[ 1  2 43]
 [ 3  4  4]]


In [22]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [24]:
a[2:4]

array([3, 4])

In [25]:
a[1:4]

array([2, 3, 4])

In [26]:
a[1:]

array([2, 3, 4, 5])

In [27]:
a[::]

array([1, 2, 3, 4, 5])

In [28]:
a[:]

array([1, 2, 3, 4, 5])

In [29]:
a[::-1]

array([5, 4, 3, 2, 1])

In [30]:
a[-2:]

array([4, 5])

In [31]:
a[-1:]

array([5])

In [32]:
a[-2:-1]

array([4])

In [34]:
a[:-2]

array([1, 2, 3])

In [38]:
# create a 2*2 matrix in numpy
import numpy as np
matrix1=np.array([[1,2],[2,4]])
print("2*2 matrix:\n",matrix1)


2*2 matrix:
 [[1 2]
 [2 4]]


In [40]:
matrix2=np.array([[1,2,6],[2,4,8],[3,5,9]])
print("3*3 matrix:\n",matrix2)

3*3 matrix:
 [[1 2 6]
 [2 4 8]
 [3 5 9]]


In [46]:
a=np.array([[1,3,4],[4,5,6],[7,8,9]])
b=np.array([[2,3,4],[6,7,9],[4,6,9]])
print(a)
print()
print(b)
print()
c=a+b

print(c)

[[1 3 4]
 [4 5 6]
 [7 8 9]]

[[2 3 4]
 [6 7 9]
 [4 6 9]]

[[ 3  6  8]
 [10 12 15]
 [11 14 18]]


In [3]:
# create two matrix 
import numpy as np
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])
result=np.dot(matrix1,matrix2)
print("atrix1*matrix2:\n",result)

atrix1*matrix2:
 [[14 30]
 [38 86]]


In [5]:
# create a matrix
matrix1=np.array([[1,3],[5,7],[9,8]])
print(matrix1)
print()
#get transpose of matrix1
result =np.transpose(matrix1)
print(result)


[[1 3]
 [5 7]
 [9 8]]

[[1 5 9]
 [3 7 8]]


In [6]:
import numpy as np
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
np.hstack((x,y))

[3 5 7]

[5 7 9]



array([3, 5, 7, 5, 7, 9])

In [8]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
np.hstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]



array([[3, 5],
       [5, 7],
       [7, 9]])

In [9]:
import numpy as np
x=np.array([3,5,7])
print(x)
print()
y=np.array([5,7,9])
print(y)
print()
np.vstack((x,y))

[3 5 7]

[5 7 9]



array([[3, 5, 7],
       [5, 7, 9]])

In [11]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
np.vstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]



array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

In [7]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
x.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [12]:
x=np.array([[1,11,12,13],[2,43,44,28],[31,32,34,35],[41,42,43,44]])
print(x)


[[ 1 11 12 13]
 [ 2 43 44 28]
 [31 32 34 35]
 [41 42 43 44]]


In [13]:
x.ndim

2

In [10]:
print(x[1:3,0:2])

[[ 2 23]
 [31 32]]


In [15]:
np.sort(x,axis=0)

array([[ 1, 11, 12, 13],
       [ 2, 32, 34, 28],
       [31, 42, 43, 35],
       [41, 43, 44, 44]])

In [16]:
a=np.array([1,4,5,6,79,66,4,])
print(a)

[ 1  4  5  6 79 66  4]


In [17]:
a.argmax()

4

In [18]:
a.argsort()

array([0, 1, 6, 2, 3, 5, 4], dtype=int64)

In [19]:
a[a.argsort()]

array([ 1,  4,  4,  5,  6, 66, 79])

In [1]:
#conditional selection 
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [3]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [4]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a[a==5]

array([5])

In [9]:
a[a<5]

array([1, 2, 3, 4])

In [11]:
a[a%2!=0]=0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [12]:
import numpy as np
a=np.array([1,2,3,4,5,2])
print(a)


[1 2 3 4 5 2]


In [14]:
a.ndim

1

In [15]:
a.shape

(6,)

In [16]:
np.where(a==3)

(array([2], dtype=int64),)

In [17]:
np.where(a==2)

(array([1, 5], dtype=int64),)

In [18]:
#odd number 
np.where(a%2!=0)

(array([0, 2, 4], dtype=int64),)

In [19]:
#searchsorted
a=np.array([1,2,3,4,10,11,15])
print(a)

[ 1  2  3  4 10 11 15]


In [21]:
np.searchsorted(a,8)

4

In [22]:
np.searchsorted(a,12)

6

In [24]:
import time 
import sys
sys.getsizeof(1000)

28

In [26]:
a=range(200000)
print(sys.getsizeof(2)*len(a))

5600000


In [27]:
a=np.arange(200000)
a.itemsize

4

In [28]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


In [30]:
a1=range(1000000)
b1=range(1000000)
start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken :" ,(time.time()-start)*1000)

time taken : 286.4561080932617


In [31]:
#fast
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()
c2=a2+b2
print("time taken  by array :",(time.time()-start)*1000)

time taken  by array : 3.5986900329589844


In [32]:
#convininent
n1=np.arange(100)
n2=np.arange(100)
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [33]:
# shallow copy
ls=[12,23,34,45,56,78]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[3]="nishant"
print(ls)
print(ls1)

[12, 23, 34, 45, 56, 78]
[12, 23, 34, 45, 56, 78]
[12, 23, 34, 45, 56, 78]
[12, 23, 34, 'nishant', 56, 78]


In [35]:
ls=[[12,23,34],[45,56,78]]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[0][1]="nishant"
print(ls)
print(ls1)

[[12, 23, 34], [45, 56, 78]]
[[12, 23, 34], [45, 56, 78]]
[[12, 'nishant', 34], [45, 56, 78]]
[[12, 'nishant', 34], [45, 56, 78]]


In [37]:
import copy
ls=[[12,23,34],[45,56,78]]
ls1=copy.deepcopy(ls)
print(ls)
print(ls1)
ls1[0][1]="nishant"
print(ls)
print(ls1)

[[12, 23, 34], [45, 56, 78]]
[[12, 23, 34], [45, 56, 78]]
[[12, 23, 34], [45, 56, 78]]
[[12, 'nishant', 34], [45, 56, 78]]


In [2]:
# how fetch random number interger in numpy

import numpy as np
#generate random interger from 0 to 9
random_number =np.random.randint(0,10)
print(random_number)



5


In [4]:
#note : we can also import and use the random module like this:
from numpy import random 
random_number=random.randint(0,10)
print(random_number)
     

8


In [6]:
import numpy as np
#generate random float -point number between 0 and 1
random_number= np.random.rand()
print(random_number)

0.6306908801341052


In [8]:
import numpy as np
#generate id array of 5 random integer between 0 and 9
integer_array=np.random.randint(0,10,5)
print("1d random integer array:\n",integer_array)

1d random integer array:
 [0 7 9 8 3]


In [9]:
#generate id array of 5 random number between 0 and 1
float_array=np.random.rand(5)
print("\n1d random float array:\n",float_array)


1d random float array:
 [0.38028254 0.45438981 0.08533291 0.80757052 0.20450449]


In [13]:
# generate 2d array of shape (3,4)with random interger 
result=np.random.randint(0,10,(10,12))
print("\n2d random integer array :\n",result)


2d random integer array :
 [[8 0 8 5 5 9 8 3 1 3 9 0]
 [4 0 8 8 4 4 8 8 2 5 1 1]
 [4 8 3 9 9 8 8 1 1 8 7 7]
 [1 9 0 7 1 8 2 6 8 5 2 8]
 [4 4 1 2 0 2 2 5 6 1 4 6]
 [6 2 7 8 8 1 9 0 7 8 1 6]
 [6 5 6 9 7 3 4 6 0 8 2 4]
 [7 7 2 4 6 4 4 9 2 2 2 7]
 [2 7 5 1 6 4 1 5 7 4 0 7]
 [1 8 0 3 4 1 6 3 5 5 3 8]]


In [15]:
# create an array of integer from 1 to 5
array1=np.array([1,3,4,5,6,7])
#choose a random number from array1
random_choice=np.random.choice(array1)
print(random_choice)

4


In [28]:
import numpy as np 
from numpy.random import randint as ri 
#np.random.seed(100)
np.random.seed(1)
ri(1,100,(5,6))

array([[38, 13, 73, 10, 76,  6],
       [80, 65, 17,  2, 77, 72],
       [ 7, 26, 51, 21, 19, 85],
       [12, 29, 30, 15, 51, 69],
       [88, 88, 95, 97, 87, 14]])

In [30]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
